# SPDX-FileCopyrightText: 2023 LakeSoul Contributors
#
# SPDX-License-Identifier: Apache-2.0

version: '3'

services:
  postgres:
    image: postgres:14.5
    container_name: doris-lakesoul-pg
    hostname: ${LAKESOUL_META_HOST}
    networks:
      - doris-lakesoul
    ports:
      - "${PG_PORT}:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: lakesoul_test
      POSTGRES_USER: lakesoul_test
      POSTGRES_DB: lakesoul_test
    command:
      - "postgres"
      - "-c"
      - "max_connections=4096"
      - "-c"
      - "default_transaction_isolation=serializable"
    volumes:
      - ./sql/meta_init.sql:/docker-entrypoint-initdb.d/meta_init.sql
      - ./sql/meta_cleanup.sql:/meta_cleanup.sql

  doris:
    image: swr.cn-southwest-2.myhuaweicloud.com/dmetasoul-repo/hadoop-env:3.1.1
    container_name: doris-lakesoul-doris
    networks:
      - doris-lakesoul
    hostname: doris
    user: root
    ports:
      - ${DORIS_QUERY_PORT}:9030
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - LD_LIBRARY_PATH=/opt/doris/be/lib
      - JAVA_HOME=/opt/jdk-17
      
    volumes:
      - ./packages/jdk-17:/opt/jdk-17
      - ./packages/doris-bin:/opt/doris-bin
      - ./sql/init_doris.sql:/opt/doris-bin/init_doris.sql
      - ./scripts:/opt/scripts
    command: bin/bash /opt/scripts/start_doris.sh

  mysql:
    image: mysql:8
    restart: always
    container_name: doris-lakesoul-mysql-source
    networks:
      - doris-lakesoul
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_cdc
    command:
      --max_connections=4096
    volumes:
      - ./sql/mysql_init.sql:/docker-entrypoint-initdb.d/mysql_init.sql
      - ./packages/mysql_random_data_load:/mysql_random_data_load
      - ./scripts/2_insert_table_data.sh:/2_insert_table_data.sh
      - ./conf/properties:/properties

  minio:
    image: bitnami/minio:latest
    container_name: doris-lakesoul-minio
    ports:
      - ${MINIO_API_PORT}:9000
      - ${MINIO_UI_PORT}:9001
    environment:
      MINIO_DEFAULT_BUCKETS: lakesoul-test-bucket:public
      MINIO_ROOT_USER: minioadmin1
      MINIO_ROOT_PASSWORD: minioadmin1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 3s
      timeout: 5s
      retries: 3
    hostname: minio
    networks:
      - doris-lakesoul
    # profiles: ["s3"]

  jobmanager:
    image: flink:1.17.1-scala_2.12-java8
    container_name: doris-lakesoul-jobmanager
    ports:
      - ${FLINK_JOBMANAGER_PORT}:8081
    command: jobmanager
    networks:
      - doris-lakesoul
    depends_on:
      - minio
    deploy:
      replicas: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.memory.process.size: 3000m
        taskmanager.memory.flink.size: 2048m
        s3.endpoint: http://minio:9000
        s3.access-key: minioadmin1
        s3.secret-key: minioadmin1
        s3.path.style.access: true
      - LAKESOUL_PG_DRIVER=com.lakesoul.shaded.org.postgresql.Driver
      - LAKESOUL_PG_URL=jdbc:postgresql://${LAKESOUL_META_HOST}:5432/lakesoul_test?stringtype=unspecified
      - LAKESOUL_PG_USERNAME=lakesoul_test
      - LAKESOUL_PG_PASSWORD=lakesoul_test
      - FLINK_HOME=/opt/flink
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_CLASSPATH="/opt/hadoop/etc/hadoop:/opt/hadoop/share/hadoop/common/lib/*:/opt/hadoop/share/hadoop/common/*:/opt/hadoop/share/hadoop/hdfs:/opt/hadoop/share/hadoop/hdfs/lib/*:/opt/hadoop/share/hadoop/hdfs/*:/opt/hadoop/share/hadoop/mapreduce/*:/opt/hadoop/share/hadoop/yarn:/opt/hadoop/share/hadoop/yarn/lib/*:/opt/hadoop/share/hadoop/yarn/*"
    volumes:
      - ./work-dir/:/opt/flink/work-dir/
      - ./packages/hadoop-3.3.5:/opt/hadoop
      - ./packages/jars/lakesoul-flink-1.17-2.6.1.jar:/opt/flink/lib/lakesoul-flink-1.17-2.6.1.jar
      - ./packages/jars/flink-s3-fs-hadoop-1.17.1.jar:/opt/flink/plugins/s3/flink-s3-fs-hadoop-1.17.1.jar
      - ./packages/jars/flink-parquet-1.17.1.jar:/opt/flink/lib/flink-parquet-1.17.1.jar
      - ./packages/jars/parquet-hadoop-bundle-1.12.3.jar:/opt/flink/lib/parquet-hadoop-bundle-1.12.3.jar
      - ./sql/init_flink_tables.sql:/opt/flink/sql/init_tables.sql


  taskmanager:
    image: flink:1.17.1-scala_2.12-java8
    depends_on:
      - jobmanager
    command: taskmanager
    deploy:
      replicas: 2
    networks:
      - doris-lakesoul
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.memory.process.size: 3000m
        taskmanager.memory.flink.size: 2048m
        taskmanager.numberOfTaskSlots: 6
        s3.endpoint: http://minio:9000
        s3.access-key: minioadmin1
        s3.secret-key: minioadmin1
        s3.path.style.access: true
      - LAKESOUL_PG_DRIVER=com.lakesoul.shaded.org.postgresql.Driver
      - LAKESOUL_PG_URL=jdbc:postgresql://${LAKESOUL_META_HOST}:5432/lakesoul_test?stringtype=unspecified
      - LAKESOUL_PG_USERNAME=lakesoul_test
      - LAKESOUL_PG_PASSWORD=lakesoul_test
      - FLINK_HOME=/opt/flink
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_CLASSPATH="/opt/hadoop/etc/hadoop:/opt/hadoop/share/hadoop/common/lib/*:/opt/hadoop/share/hadoop/common/*:/opt/hadoop/share/hadoop/hdfs:/opt/hadoop/share/hadoop/hdfs/lib/*:/opt/hadoop/share/hadoop/hdfs/*:/opt/hadoop/share/hadoop/mapreduce/*:/opt/hadoop/share/hadoop/yarn:/opt/hadoop/share/hadoop/yarn/lib/*:/opt/hadoop/share/hadoop/yarn/*"
    volumes:
      - ./work-dir/:/opt/flink/work-dir/
      - ./packages/hadoop-3.3.5:/opt/hadoop
      - ./packages/jars/lakesoul-flink-1.17-2.6.1.jar:/opt/flink/lib/lakesoul-flink-1.17-2.6.1.jar
      - ./packages/jars/flink-s3-fs-hadoop-1.17.1.jar:/opt/flink/plugins/s3/flink-s3-fs-hadoop-1.17.1.jar
      - ./packages/jars/flink-parquet-1.17.1.jar:/opt/flink/lib/flink-parquet-1.17.1.jar
      - ./packages/jars/parquet-hadoop-bundle-1.12.3.jar:/opt/flink/lib/parquet-hadoop-bundle-1.12.3.jar

networks:
  doris-lakesoul:
    ipam:
      driver: default